[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100

[environments.production]
variables = [
    { name = "ALLOWED_HOSTS", value = ".railway.app" },
    { name = "ENVIRONMENT", value = "production" }
]
