[build]
builder = "dockerfile"

[deploy]
healthcheckPath = /healthcheck
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = [
    { name = "ENVIRONMENT", value = "production" },
    { name = "DJANGO_SETTINGS_MODULE", value = "core.settings.production" }
]
