[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = [
    { name = "ALLOWED_HOSTS", value = "form-to-pdf-production.up.railway.app,healthcheck.railway.app" },
    { name = "ENVIRONMENT", value = "production" },
    { name = "DJANGO_SETTINGS_MODULE", value = "core.settings.production" }
]
